# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdfaa46d16aa1f808c8fa883c6d5816f30b18cc72d5873c2769d98599bb1867f2919f405ece5b400e91d7f0c2ed606fba0b37b719c71342550f28be763d562c3

test:
  secret_key_base: 19a14b9a942226ab9d8149b77a7117b49839fe57033557e5165ef98f4aca1f0060ee0804f481c03b1a19b1857a33799076cb8887cd2b21e9ad99a0cbbfbfaa22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
